### ISSUE TITLE
Saving `pde.ScalarField` via `result.to_file` does not work

### ISSUE THREAD

**Issue by friederjohannsen** [zwicker-group/py-modelrunner#42]
When trying to save a `pde.ScalarField` (e.g. a resulting field from a simulation), the following error is thrown: `TypeError: Object of type ScalarField is not JSON serializable`.

Minimal example:
```python
class MyModel(ModelBase):
    ...
    def __call__(self):
        ...
        initial_state = pde.ScalarField(...)
        final_state = eq.solve(initial_state, ...)
        result = {"final_state": final_state}
        return result
...
if __name__ == "__main__":
    submit_jobs(
        __file__,
        method='foreground',
        ...
    )
```
will write the mentioned error (+ traceback) to the error logfile. The resulting .hdf file will not contain data.

**Comment by david-zwicker** [comment]
I looked into this problem and I'm not surprised that `py-modelrunner` does not support `py-pde` fields correctly since these two packages are completely independent for now. In the (far) future, I would like to base `py-pde` on `py-modelrunner`, which would automatically give full support for writing fields, but I don't have concrete plans for this transition, yet.

In the meantime, you could write your output to `zarr` files, which by some python magic already support complex python objects, including `py-pde` fields. You can use the argument `output_format="zarr"` in your call to `submit_jobs` to set the output format.

**Comment by david-zwicker** [comment]
The latest update to `py-modelrunner` should now support saving arbitrary python objects, thus also supporting `pde.ScalarField`. Note that this is not tested very well, though.
